name: Documents

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - Document

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  update-document:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Create pull request
    if: github.event.action == 'Document'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure doc branch exists and has changes
        run: |
          doc_branch=automation/task/update-rfw-libdoc-documents
          git fetch origin $doc_branch || git checkout -b $doc_branch
          git checkout $doc_branch
          # Make sure there are changes
          if [ "$(git rev-list develop..$doc_branch)" == "" ]; then
            echo "No changes between develop and $doc_branch. Skipping PR creation."
            exit 0
          fi
          git push origin $doc_branch

      - name: Create pull request
        run: |
          doc_branch=automation/task/update-rfw-libdoc-documents

          echo "Create pull request to merge documents"
          pr_exists=$(gh pr list --state open | grep -qw "Updating generated libdoc documents" && echo "found" || echo "not found")
          if [ "$pr_exists" == "not found" ]; then
            # Pull request not exist
            echo "Pull request not found. Creating a new one..."
            gh pr create \
            --base develop --head $doc_branch \
            --title "Updating generated libdoc documents" \
            --body "This PR was automatically generated by GitHub Actions to update documents" \
            --assignee test-fullautomation \
            --reviewer trimai3001 \
            --reviewer ngoan1608
          else
            echo "Pull request already exists. Skipping..."
          fi
