name: Deploy via SFTP

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
         fetch-depth: 0

    - name: Upload files via SFTP
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: "ssh.strato.de"
        remote-user: "upload@robotframework-aio.org"
        remote-password: ${{ secrets.SFTP_PASSWORD }}
        remote-path: "/"
        sync: "full"