name: Deploy via SFTP

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload files via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ssh.strato.de
        username: upload@robotframework-aio.org
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "*"
        target: "/"
